apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-monorepo-app-b
  namespace: min-side
  labels:
    team: min-side
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi